on:
  push:
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '**.toml'
      - '**.md'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '**.toml'
      - '**.md'
  workflow_dispatch:

name: CI

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Run flake8
        uses: julianwachholz/flake8-action@v2
        with:
          checkName: "Python Lint"
          path: src/
      - name: Run Docker lint
        uses: ghe-actions/dockerfile-validator@v1
        with:
          dockerfile: 'Dockerfile'
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.1.5"
      - name: Install depepdencies
        run: poetry install
      - name: Run test
        run: poetry run python test.py
      